/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiket.kereta.api.nadia;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Nadia Putri
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtawal = new javax.swing.JTextField();
        txttujuan = new javax.swing.JTextField();
        Tanggal = new com.toedter.calendar.JDateChooser();
        cbTempat = new javax.swing.JComboBox<>();
        cbJenis = new javax.swing.JComboBox<>();
        txtwaktu = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReload = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 51, 0));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(204, 204, 0));
        jPanel3.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Nama");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 10, 70, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("No ID");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 70, 70, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setText("Stasiun Awal");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 130, 120, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel8.setText("Stasiun Tujuan");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(10, 200, 120, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel9.setText("Tanggal Keberangkatan");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(10, 270, 170, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel10.setText("Jenis Kereta");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(320, 10, 110, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel11.setText("Waktu Berangkat");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(320, 70, 140, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel12.setText("Tempat Duduk");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(320, 130, 170, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel13.setText("Harga");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(320, 200, 80, 30);
        jPanel3.add(txtid);
        txtid.setBounds(10, 100, 240, 30);
        jPanel3.add(txtnama);
        txtnama.setBounds(10, 40, 240, 30);
        jPanel3.add(txtawal);
        txtawal.setBounds(10, 160, 240, 30);
        jPanel3.add(txttujuan);
        txttujuan.setBounds(10, 230, 240, 30);
        jPanel3.add(Tanggal);
        Tanggal.setBounds(10, 300, 240, 30);

        cbTempat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerbong Anda", "Gerbong 01", "Gerbong 02", "Gerbong 03", "Gerbong 04", "Gerbong 05", "Gerbong 06", "Gerbong 07" }));
        jPanel3.add(cbTempat);
        cbTempat.setBounds(320, 160, 240, 30);

        cbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Kereta Anda --", "Argo Wilis", "Gajayana", "Sembrani", "Lodaya", "Malabar", "Majapahit", "Senja Utama" }));
        jPanel3.add(cbJenis);
        cbJenis.setBounds(320, 40, 240, 30);
        jPanel3.add(txtwaktu);
        txtwaktu.setBounds(320, 100, 240, 30);
        jPanel3.add(txtharga);
        txtharga.setBounds(320, 230, 240, 30);

        Table.setBackground(new java.awt.Color(204, 204, 0));
        Table.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "NoID", "StasiunAwal", "StasiunTujuan", "TanggalBerangkat", "JenisKereta", "WaktuBerangkat", "TempatDuduk", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Table);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 340, 930, 220);

        btnSave.setBackground(new java.awt.Color(153, 153, 0));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel3.add(btnSave);
        btnSave.setBounds(280, 300, 70, 30);

        btnClear.setBackground(new java.awt.Color(153, 153, 0));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel3.add(btnClear);
        btnClear.setBounds(360, 300, 70, 30);

        btnDelete.setBackground(new java.awt.Color(153, 153, 0));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btnDelete);
        btnDelete.setBounds(440, 300, 70, 30);

        btnReload.setBackground(new java.awt.Color(153, 153, 0));
        btnReload.setText("Reload");
        btnReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadActionPerformed(evt);
            }
        });
        jPanel3.add(btnReload);
        btnReload.setBounds(600, 300, 70, 30);

        btnPrint.setBackground(new java.awt.Color(153, 153, 0));
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel3.add(btnPrint);
        btnPrint.setBounds(520, 300, 70, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(40, 56, 950, 570);

        jPanel4.setBackground(new java.awt.Color(153, 153, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FORM PEMESANAN TIKET");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(402, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(365, 365, 365))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel2))
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(40, 11, 950, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 1000, 640);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RESERVASI TIKET KERETA API");

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("nikmati perjalanan aman dan nyaman sampai tujuan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(603, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1000, 70);

        setSize(new java.awt.Dimension(1017, 748));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(Tanggal.getDate());
        
        String JenisKereta = "";
            if(cbJenis.getSelectedItem().equals("Argo Wilis")) {
                JenisKereta = "Argo Wilis";
            }else if(cbJenis.getSelectedItem().equals("Gajayana")) {
                JenisKereta = "Gajayana";
            }else if(cbJenis.getSelectedItem().equals("Sembrani")) {
                JenisKereta = "Sembrani";
            }else if(cbJenis.getSelectedItem().equals("Lodaya")) {
                JenisKereta = "Lodaya";
            }else if(cbJenis.getSelectedItem().equals("Malabar")) {
                JenisKereta = "Malabar";
            }else if(cbJenis.getSelectedItem().equals("Majapahit")) {
                JenisKereta = "Majapahit";
            }else {
                JenisKereta = "Senja Utama";
            }
        
            
               
            String TempatDuduk = "";
            if(cbTempat.getSelectedItem().equals("Gerbong 01")) {
                TempatDuduk = "Gerbong 01";
            }else if(cbTempat.getSelectedItem().equals("Gerbong 02")) {
                TempatDuduk = "Gerbong 02";
            }else if(cbTempat.getSelectedItem().equals("Gerbong 03")) {
                TempatDuduk = "Gerbong 03";
            }else if(cbTempat.getSelectedItem().equals("Gerbong 04")) {
                TempatDuduk = "Gerbong 04";
            }else if(cbTempat.getSelectedItem().equals("Gerbong 05")) {
                TempatDuduk = "Gerbong 05";
            }else if(cbTempat.getSelectedItem().equals("Gerbong 06")) {
                TempatDuduk = "Gerbong 06";
            }else {
                TempatDuduk = "Gerbong 07";
            }
         
            
          if ("".equals(txtnama.getText()) || "".equals(txtid.getText()) ||
                "".equals(txtawal.getText()) || "".equals(txttujuan.getText()) || TempatDuduk.equals("") ||
                "".equals(txtwaktu.getText()) || "".equals(txtharga.getText()) || JenisKereta.equals("") ||
                "".equals(Tanggal)) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi data", "Error", JOptionPane.WARNING_MESSAGE);
        }else {
            
            String SQL = "INSERT INTO `tb_pesan`(Nama,NoID,JenisKereta,StasiunAwal,StasiunTujuan,TanggalBerangkat,WaktuBerangkat,Harga,TempatDuduk) "
                    + "VALUES(NULL,'"+txtnama.getText()+"','"+txtid.getText()+"','"+JenisKereta+"',"
                    + "'"+txtawal.getText()+"','"+txttujuan.getText()+"','"+txtwaktu.getText()+"',"
                    + "'"+Tanggal+"','"+TempatDuduk+"',"
                    + txtharga.getText()+"')";
            
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "GAGAL", JOptionPane.WARNING_MESSAGE);
            }   
        }
    }//GEN-LAST:event_btnSaveActionPerformed


    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtnama.setText("");
        txtid.setText("");
        txtawal.setText("");
        txttujuan.setText("");
        txtwaktu.setText("");
        txtharga.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_btnReloadActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int baris = Table.getSelectedRow();
        if (baris != -1) {
            String Nama = Table.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM 'tb_pesan' WHERE Nama='"+Nama+"'";
            int status = KoneksiDB.execute(SQL);
            if(status==1) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }else {
                JOptionPane.showMessageDialog(this, "Data Gagal Dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }else {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Tiket Kereta Api Indonesia");
        MessageFormat footer = new MessageFormat("Page {0,number,integer} ");
        try {
            Table.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }
        catch (java.awt.print.PrinterException e) {
            System.err.format("Can't print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private com.toedter.calendar.JDateChooser Tanggal;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnReload;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbJenis;
    private javax.swing.JComboBox<String> cbTempat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtawal;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txttujuan;
    private javax.swing.JTextField txtwaktu;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"Nama","NoID","StasiunAwal","StasiunTujuan","TanggalBerangkat","JenisKereta","WaktuBerangkat","TempatDuduk","Harga"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM 'tb_pesan'";
        ResultSet rs = KoneksiDB.excecuteQuery(SQL);
        try {
            while(rs.next()) {
                String Nama = rs.getString(1);
                String NoID = rs.getString(2);
                String StasiunAwal = rs.getString(3);
                String StasiunTujuan = rs.getString(4);
                String TanggalBerangkat = rs.getString(5);
                String JenisKereta = "";
            if(cbJenis.getSelectedItem().equals("Argo Wilis")) {
                JenisKereta = "Argo Wilis";
            }else if(cbJenis.getSelectedItem().equals("Gajayana")) {
                JenisKereta = "Gajayana";
            }else if(cbJenis.getSelectedItem().equals("Sembrani")) {
                JenisKereta = "Sembrani";
            }else if(cbJenis.getSelectedItem().equals("Lodaya")) {
                JenisKereta = "Lodaya";
            }else if(cbJenis.getSelectedItem().equals("Malabar")) {
                JenisKereta = "Malabar";
            }else if(cbJenis.getSelectedItem().equals("Majapahit")) {
                JenisKereta = "Majapahit";
            }else {
                JenisKereta = "Senja Utama";
            }
            String WaktuBerangkat = rs.getString(7);
            String TempatDuduk = "";
            if(cbTempat.getSelectedItem().equals("Gerbong 01")) {
                TempatDuduk = "Gerbong 01";
            }else if(cbTempat.getSelectedItem().equals("Gerbong 02")) {
                TempatDuduk = "Gerbong 02";
            }else if(cbTempat.getSelectedItem().equals("Gerbong 03")) {
                TempatDuduk = "Gerbong 03";
            }else if(cbTempat.getSelectedItem().equals("Gerbong 04")) {
                TempatDuduk = "Gerbong 04";
            }else if(cbTempat.getSelectedItem().equals("Gerbong 05")) {
                TempatDuduk = "Gerbong 05";
            }else if(cbTempat.getSelectedItem().equals("Gerbong 06")) {
                TempatDuduk = "Gerbong 06";
            }else {
                TempatDuduk = "Gerbong 07";
            }
            String Harga = rs.getString(9);
                String data[] = {Nama,NoID,StasiunAwal,StasiunTujuan,TanggalBerangkat,JenisKereta,WaktuBerangkat,TempatDuduk,Harga};
                dtm.addRow(data);
            }
                }catch (SQLException ex) {
                    Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
                }
        Table.setModel(dtm);   
            }
        }